# Generated by Django 4.2 on 2023-07-20 00:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('altera_senha', models.BooleanField(default=True, verbose_name='Altera Senha Proximo Login?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador?')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'auth_user',
            },
        ),
    ]
